### ISSUE TITLE
Implement StraightLine

### ISSUE THREAD

**Issue by Sakorni** [mmcs-ruby/primitives#8]
For mirror method we need a line.
- [ ] Write Line interface with "Not implemented" methods
- [ ] Write tests for an interface methods
- [ ] Implement methods
- [ ] Write tests for equation below
- [ ] Write the equation to find a shorter distance from Point to Line

**Comment by Wolwer1nE** [comment]
Line is an object described by `k*x+b`
We need validation for inputs
Check if lines are intersecting
And distance from last line in issue.
